// source: tendermint/p2p/types.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var gogoproto_gogo_pb = require('../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.tendermint.p2p.NodeInfo', null, global);
goog.exportSymbol('proto.tendermint.p2p.NodeInfoOther', null, global);
goog.exportSymbol('proto.tendermint.p2p.PeerAddressInfo', null, global);
goog.exportSymbol('proto.tendermint.p2p.PeerInfo', null, global);
goog.exportSymbol('proto.tendermint.p2p.ProtocolVersion', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tendermint.p2p.ProtocolVersion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tendermint.p2p.ProtocolVersion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tendermint.p2p.ProtocolVersion.displayName = 'proto.tendermint.p2p.ProtocolVersion';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tendermint.p2p.NodeInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tendermint.p2p.NodeInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tendermint.p2p.NodeInfo.displayName = 'proto.tendermint.p2p.NodeInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tendermint.p2p.NodeInfoOther = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tendermint.p2p.NodeInfoOther, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tendermint.p2p.NodeInfoOther.displayName = 'proto.tendermint.p2p.NodeInfoOther';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tendermint.p2p.PeerInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tendermint.p2p.PeerInfo.repeatedFields_, null);
};
goog.inherits(proto.tendermint.p2p.PeerInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tendermint.p2p.PeerInfo.displayName = 'proto.tendermint.p2p.PeerInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tendermint.p2p.PeerAddressInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tendermint.p2p.PeerAddressInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tendermint.p2p.PeerAddressInfo.displayName = 'proto.tendermint.p2p.PeerAddressInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tendermint.p2p.ProtocolVersion.prototype.toObject = function(opt_includeInstance) {
  return proto.tendermint.p2p.ProtocolVersion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tendermint.p2p.ProtocolVersion} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.p2p.ProtocolVersion.toObject = function(includeInstance, msg) {
  var f, obj = {
    p2p: jspb.Message.getFieldWithDefault(msg, 1, 0),
    block: jspb.Message.getFieldWithDefault(msg, 2, 0),
    app: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tendermint.p2p.ProtocolVersion}
 */
proto.tendermint.p2p.ProtocolVersion.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tendermint.p2p.ProtocolVersion;
  return proto.tendermint.p2p.ProtocolVersion.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tendermint.p2p.ProtocolVersion} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tendermint.p2p.ProtocolVersion}
 */
proto.tendermint.p2p.ProtocolVersion.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setP2p(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBlock(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setApp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tendermint.p2p.ProtocolVersion.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tendermint.p2p.ProtocolVersion.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tendermint.p2p.ProtocolVersion} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.p2p.ProtocolVersion.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getP2p();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getBlock();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getApp();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
};


/**
 * optional uint64 p2p = 1;
 * @return {number}
 */
proto.tendermint.p2p.ProtocolVersion.prototype.getP2p = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.tendermint.p2p.ProtocolVersion} returns this
 */
proto.tendermint.p2p.ProtocolVersion.prototype.setP2p = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint64 block = 2;
 * @return {number}
 */
proto.tendermint.p2p.ProtocolVersion.prototype.getBlock = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tendermint.p2p.ProtocolVersion} returns this
 */
proto.tendermint.p2p.ProtocolVersion.prototype.setBlock = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 app = 3;
 * @return {number}
 */
proto.tendermint.p2p.ProtocolVersion.prototype.getApp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.tendermint.p2p.ProtocolVersion} returns this
 */
proto.tendermint.p2p.ProtocolVersion.prototype.setApp = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tendermint.p2p.NodeInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.tendermint.p2p.NodeInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tendermint.p2p.NodeInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.p2p.NodeInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    protocolVersion: (f = msg.getProtocolVersion()) && proto.tendermint.p2p.ProtocolVersion.toObject(includeInstance, f),
    nodeId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    listenAddr: jspb.Message.getFieldWithDefault(msg, 3, ""),
    network: jspb.Message.getFieldWithDefault(msg, 4, ""),
    version: jspb.Message.getFieldWithDefault(msg, 5, ""),
    channels: msg.getChannels_asB64(),
    moniker: jspb.Message.getFieldWithDefault(msg, 7, ""),
    other: (f = msg.getOther()) && proto.tendermint.p2p.NodeInfoOther.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tendermint.p2p.NodeInfo}
 */
proto.tendermint.p2p.NodeInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tendermint.p2p.NodeInfo;
  return proto.tendermint.p2p.NodeInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tendermint.p2p.NodeInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tendermint.p2p.NodeInfo}
 */
proto.tendermint.p2p.NodeInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tendermint.p2p.ProtocolVersion;
      reader.readMessage(value,proto.tendermint.p2p.ProtocolVersion.deserializeBinaryFromReader);
      msg.setProtocolVersion(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setListenAddr(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNetwork(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setChannels(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setMoniker(value);
      break;
    case 8:
      var value = new proto.tendermint.p2p.NodeInfoOther;
      reader.readMessage(value,proto.tendermint.p2p.NodeInfoOther.deserializeBinaryFromReader);
      msg.setOther(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tendermint.p2p.NodeInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tendermint.p2p.NodeInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tendermint.p2p.NodeInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.p2p.NodeInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProtocolVersion();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.tendermint.p2p.ProtocolVersion.serializeBinaryToWriter
    );
  }
  f = message.getNodeId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getListenAddr();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNetwork();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getChannels_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      6,
      f
    );
  }
  f = message.getMoniker();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getOther();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.tendermint.p2p.NodeInfoOther.serializeBinaryToWriter
    );
  }
};


/**
 * optional ProtocolVersion protocol_version = 1;
 * @return {?proto.tendermint.p2p.ProtocolVersion}
 */
proto.tendermint.p2p.NodeInfo.prototype.getProtocolVersion = function() {
  return /** @type{?proto.tendermint.p2p.ProtocolVersion} */ (
    jspb.Message.getWrapperField(this, proto.tendermint.p2p.ProtocolVersion, 1));
};


/**
 * @param {?proto.tendermint.p2p.ProtocolVersion|undefined} value
 * @return {!proto.tendermint.p2p.NodeInfo} returns this
*/
proto.tendermint.p2p.NodeInfo.prototype.setProtocolVersion = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.p2p.NodeInfo} returns this
 */
proto.tendermint.p2p.NodeInfo.prototype.clearProtocolVersion = function() {
  return this.setProtocolVersion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.p2p.NodeInfo.prototype.hasProtocolVersion = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string node_id = 2;
 * @return {string}
 */
proto.tendermint.p2p.NodeInfo.prototype.getNodeId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.tendermint.p2p.NodeInfo} returns this
 */
proto.tendermint.p2p.NodeInfo.prototype.setNodeId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string listen_addr = 3;
 * @return {string}
 */
proto.tendermint.p2p.NodeInfo.prototype.getListenAddr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.tendermint.p2p.NodeInfo} returns this
 */
proto.tendermint.p2p.NodeInfo.prototype.setListenAddr = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string network = 4;
 * @return {string}
 */
proto.tendermint.p2p.NodeInfo.prototype.getNetwork = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.tendermint.p2p.NodeInfo} returns this
 */
proto.tendermint.p2p.NodeInfo.prototype.setNetwork = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string version = 5;
 * @return {string}
 */
proto.tendermint.p2p.NodeInfo.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.tendermint.p2p.NodeInfo} returns this
 */
proto.tendermint.p2p.NodeInfo.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bytes channels = 6;
 * @return {!(string|Uint8Array)}
 */
proto.tendermint.p2p.NodeInfo.prototype.getChannels = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes channels = 6;
 * This is a type-conversion wrapper around `getChannels()`
 * @return {string}
 */
proto.tendermint.p2p.NodeInfo.prototype.getChannels_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getChannels()));
};


/**
 * optional bytes channels = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getChannels()`
 * @return {!Uint8Array}
 */
proto.tendermint.p2p.NodeInfo.prototype.getChannels_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getChannels()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.tendermint.p2p.NodeInfo} returns this
 */
proto.tendermint.p2p.NodeInfo.prototype.setChannels = function(value) {
  return jspb.Message.setProto3BytesField(this, 6, value);
};


/**
 * optional string moniker = 7;
 * @return {string}
 */
proto.tendermint.p2p.NodeInfo.prototype.getMoniker = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.tendermint.p2p.NodeInfo} returns this
 */
proto.tendermint.p2p.NodeInfo.prototype.setMoniker = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional NodeInfoOther other = 8;
 * @return {?proto.tendermint.p2p.NodeInfoOther}
 */
proto.tendermint.p2p.NodeInfo.prototype.getOther = function() {
  return /** @type{?proto.tendermint.p2p.NodeInfoOther} */ (
    jspb.Message.getWrapperField(this, proto.tendermint.p2p.NodeInfoOther, 8));
};


/**
 * @param {?proto.tendermint.p2p.NodeInfoOther|undefined} value
 * @return {!proto.tendermint.p2p.NodeInfo} returns this
*/
proto.tendermint.p2p.NodeInfo.prototype.setOther = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.p2p.NodeInfo} returns this
 */
proto.tendermint.p2p.NodeInfo.prototype.clearOther = function() {
  return this.setOther(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.p2p.NodeInfo.prototype.hasOther = function() {
  return jspb.Message.getField(this, 8) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tendermint.p2p.NodeInfoOther.prototype.toObject = function(opt_includeInstance) {
  return proto.tendermint.p2p.NodeInfoOther.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tendermint.p2p.NodeInfoOther} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.p2p.NodeInfoOther.toObject = function(includeInstance, msg) {
  var f, obj = {
    txIndex: jspb.Message.getFieldWithDefault(msg, 1, ""),
    rpcAddress: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tendermint.p2p.NodeInfoOther}
 */
proto.tendermint.p2p.NodeInfoOther.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tendermint.p2p.NodeInfoOther;
  return proto.tendermint.p2p.NodeInfoOther.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tendermint.p2p.NodeInfoOther} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tendermint.p2p.NodeInfoOther}
 */
proto.tendermint.p2p.NodeInfoOther.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTxIndex(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRpcAddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tendermint.p2p.NodeInfoOther.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tendermint.p2p.NodeInfoOther.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tendermint.p2p.NodeInfoOther} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.p2p.NodeInfoOther.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTxIndex();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRpcAddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string tx_index = 1;
 * @return {string}
 */
proto.tendermint.p2p.NodeInfoOther.prototype.getTxIndex = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tendermint.p2p.NodeInfoOther} returns this
 */
proto.tendermint.p2p.NodeInfoOther.prototype.setTxIndex = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string rpc_address = 2;
 * @return {string}
 */
proto.tendermint.p2p.NodeInfoOther.prototype.getRpcAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.tendermint.p2p.NodeInfoOther} returns this
 */
proto.tendermint.p2p.NodeInfoOther.prototype.setRpcAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tendermint.p2p.PeerInfo.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tendermint.p2p.PeerInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.tendermint.p2p.PeerInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tendermint.p2p.PeerInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.p2p.PeerInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    addressInfoList: jspb.Message.toObjectList(msg.getAddressInfoList(),
    proto.tendermint.p2p.PeerAddressInfo.toObject, includeInstance),
    lastConnected: (f = msg.getLastConnected()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tendermint.p2p.PeerInfo}
 */
proto.tendermint.p2p.PeerInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tendermint.p2p.PeerInfo;
  return proto.tendermint.p2p.PeerInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tendermint.p2p.PeerInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tendermint.p2p.PeerInfo}
 */
proto.tendermint.p2p.PeerInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.tendermint.p2p.PeerAddressInfo;
      reader.readMessage(value,proto.tendermint.p2p.PeerAddressInfo.deserializeBinaryFromReader);
      msg.addAddressInfo(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastConnected(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tendermint.p2p.PeerInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tendermint.p2p.PeerInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tendermint.p2p.PeerInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.p2p.PeerInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAddressInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.tendermint.p2p.PeerAddressInfo.serializeBinaryToWriter
    );
  }
  f = message.getLastConnected();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.tendermint.p2p.PeerInfo.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tendermint.p2p.PeerInfo} returns this
 */
proto.tendermint.p2p.PeerInfo.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated PeerAddressInfo address_info = 2;
 * @return {!Array<!proto.tendermint.p2p.PeerAddressInfo>}
 */
proto.tendermint.p2p.PeerInfo.prototype.getAddressInfoList = function() {
  return /** @type{!Array<!proto.tendermint.p2p.PeerAddressInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tendermint.p2p.PeerAddressInfo, 2));
};


/**
 * @param {!Array<!proto.tendermint.p2p.PeerAddressInfo>} value
 * @return {!proto.tendermint.p2p.PeerInfo} returns this
*/
proto.tendermint.p2p.PeerInfo.prototype.setAddressInfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.tendermint.p2p.PeerAddressInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tendermint.p2p.PeerAddressInfo}
 */
proto.tendermint.p2p.PeerInfo.prototype.addAddressInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.tendermint.p2p.PeerAddressInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tendermint.p2p.PeerInfo} returns this
 */
proto.tendermint.p2p.PeerInfo.prototype.clearAddressInfoList = function() {
  return this.setAddressInfoList([]);
};


/**
 * optional google.protobuf.Timestamp last_connected = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.tendermint.p2p.PeerInfo.prototype.getLastConnected = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.tendermint.p2p.PeerInfo} returns this
*/
proto.tendermint.p2p.PeerInfo.prototype.setLastConnected = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.p2p.PeerInfo} returns this
 */
proto.tendermint.p2p.PeerInfo.prototype.clearLastConnected = function() {
  return this.setLastConnected(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.p2p.PeerInfo.prototype.hasLastConnected = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.tendermint.p2p.PeerAddressInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tendermint.p2p.PeerAddressInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.p2p.PeerAddressInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: jspb.Message.getFieldWithDefault(msg, 1, ""),
    lastDialSuccess: (f = msg.getLastDialSuccess()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    lastDialFailure: (f = msg.getLastDialFailure()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    dialFailures: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tendermint.p2p.PeerAddressInfo}
 */
proto.tendermint.p2p.PeerAddressInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tendermint.p2p.PeerAddressInfo;
  return proto.tendermint.p2p.PeerAddressInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tendermint.p2p.PeerAddressInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tendermint.p2p.PeerAddressInfo}
 */
proto.tendermint.p2p.PeerAddressInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastDialSuccess(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastDialFailure(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDialFailures(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tendermint.p2p.PeerAddressInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tendermint.p2p.PeerAddressInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tendermint.p2p.PeerAddressInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLastDialSuccess();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLastDialFailure();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDialFailures();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
};


/**
 * optional string address = 1;
 * @return {string}
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tendermint.p2p.PeerAddressInfo} returns this
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp last_dial_success = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.getLastDialSuccess = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.tendermint.p2p.PeerAddressInfo} returns this
*/
proto.tendermint.p2p.PeerAddressInfo.prototype.setLastDialSuccess = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.p2p.PeerAddressInfo} returns this
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.clearLastDialSuccess = function() {
  return this.setLastDialSuccess(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.hasLastDialSuccess = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp last_dial_failure = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.getLastDialFailure = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.tendermint.p2p.PeerAddressInfo} returns this
*/
proto.tendermint.p2p.PeerAddressInfo.prototype.setLastDialFailure = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tendermint.p2p.PeerAddressInfo} returns this
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.clearLastDialFailure = function() {
  return this.setLastDialFailure(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.hasLastDialFailure = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional uint32 dial_failures = 4;
 * @return {number}
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.getDialFailures = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.tendermint.p2p.PeerAddressInfo} returns this
 */
proto.tendermint.p2p.PeerAddressInfo.prototype.setDialFailures = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


goog.object.extend(exports, proto.tendermint.p2p);
